### ISSUE TITLE
error when updating to RC 14

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-modules/algolia#108]
### Version
------------------------------
- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/algolia@1.1.5`, `@nuxtjs-alt/auth@2.1.3`, `@nuxtjs-alt/http@1.4.6`, `@nuxtjs/device@3.0.0`, `@nuxtjs/partytown@1.2.2`, `@vueuse/nuxt@9.5.0`, `nuxt-schema-org@1.1.0-beta.6`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-beta.4`
- Build Modules:    `-`
------------------------------
### Reproduction Link

I have upgraded from RC 13 to RC 14 and the server doesn't even start.

### Steps to reproduce

I have upgraded from RC 13 to RC 14 and the server doesn't even start.

### What is Expected?

 ERROR  Error while requiring module @nuxtjs/algolia: SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'addAutoImportDir'

### What is actually happening?

 ERROR  Error while requiring module @nuxtjs/algolia: SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'addAutoImportDir'

**Comment by Baroshem** [comment]
Hey, will be fixed by https://github.com/nuxt-modules/algolia/pull/107

Let's wait until friday to release a new version with the support for the stable Nuxt 3 as there might be more bugs there that needs to be solved :)
