### ISSUE TITLE
[docs] Broken website links

### ISSUE THREAD

**Issue by ennioVisco** [nuxt-modules/algolia#109]
The following links are broken in the docs:

- [Configuration > first link](https://algolia.nuxtjs.org/getting-started/configuration#:~:text=Check%20out%20more-,here,-.)
- [Usage > first link](https://algolia.nuxtjs.org/getting-started/usage#:~:text=composables%20that%20are-,auto%2Dimported,-by%20Nuxt%203)
- [Vue Instantsearch > first link](https://algolia.nuxtjs.org/advanced/vue-instantsearch#:~:text=out%20setup%20docs-,here,-Next%2C%20let%27s%20create)
- [DocSearch > third link](https://algolia.nuxtjs.org/advanced/docsearch#:~:text=%40nuxtjs/algolia%2Dmodule)
- [Crawler > first link](https://algolia.nuxtjs.org/advanced/crawler#:~:text=under%20development%20(see-,Comparison,-)) -> to substitute probably with [Nuxt > Guide > Concepts > Rendering Modes](https://nuxt.com/docs/guide/concepts/rendering)
- [Crawler > second link](https://algolia.nuxtjs.org/advanced/crawler#:~:text=this%20module%20(see-,Setup,-)%2C%20the%20module%20will)

**Comment by Baroshem** [comment]
Hey,

Thanks for crating an issue. It seems that both Nuxt 3 and Algolia have changed their structure of docs. I will fix it right after I will be back from holidays (next week)
