### ISSUE TITLE
Support for Request/Response Cashing

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt-modules/algolia#112]
It would be great to have support and possibility to turn on the Request/Response Caching from Algolia.

Official doc: https://www.algolia.com/doc/api-client/getting-started/customize/javascript/?client=javascript#caching-requests-and-responses
Reference to: https://github.com/nuxt-modules/algolia/discussions/111

**Comment by Baroshem** [comment]
I will implement it as a part of next release. 

Stay tuned!

**Comment by lukaszflorczak** [comment]
Thank you!
