### ISSUE TITLE
Get object algolia

### ISSUE THREAD

**Issue by daflav** [nuxt-modules/algolia#139]
Hello, how i can get object by id trough nuxt-algolia please ?

https://www.algolia.com/doc/api-reference/api-methods/get-objects/

**Comment by Baroshem** [comment]
Hey,

You can use the `useAlgoliaInitIndex` composable to initialize the index and then call `getObjects' from it :)

**Comment by daflav** [comment]
Hello @Baroshem  thanks for you reply.
Already tried that but i got error: getObjects its not a function

const algoliaIndex = useAlgoliaInitIndex('products')
const test = algoliaIndex.getObjects('my id')

// getObjects its not a function

**Comment by Baroshem** [comment]
Apart from that, you also need to set the `lite: false` option in module configuration as this option is only available for full version of Algolia :)

**Comment by Baroshem** [comment]
Hey @daflav 

Have you managed to make it work?
