### ISSUE TITLE
Import full algoliasearch client instead of the lite one

### ISSUE THREAD

**Issue by LoMonacoSalvatore** [nuxt-modules/algolia#140]
### Is your feature request related to a problem? Please describe.
I found myself needing to use the `getObject` and `getObjects` functions of the index, but since you are importing the lite algoliasearch client I can't use those.

### Describe the solution you'd like
Either add a module option for switching loaded client or just import the full one.

### Describe alternatives you've considered
Using the algoliasearch vanilla client

**Comment by LoMonacoSalvatore** [comment]
Found the solutions on the documents!

By default the module imports `algoliasearch-lite`, so to get access to all the functions of `algoliasearch` just set the key `lite: false` in the config options.

**Comment by Baroshem** [comment]
Hey @LoMonacoSalvatore 

This is exactly what you needed. Glad you have found it in the docs. 

Happy coding!
