### ISSUE TITLE
Axios dependency errors in storyblok-algolia-indexer when installing nuxt/algolia

### ISSUE THREAD

**Issue by digbyk** [nuxt-modules/algolia#141]
### Version

@nuxtjs/algolia: 1.5.0
nuxt: 3.3.1

### Steps to reproduce

Remove node_modules
npm i

### What is Expected?

No warnings with when installing nuxt/algolia

### What is actually happening?

I get a list of warnings when nuxt/algolia runs, mostly related to axios / storyblok. Possibly storyblok-algolia-indexer needs its dependencies updated? I don't use StoryBlok so it's not important (for me) that this bit works.

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: storyblok-js-client@4.5.8
npm WARN Found: axios@0.25.0
npm WARN node_modules/storyblok-algolia-indexer/node_modules/axios
npm WARN   axios@"^0.25.0" from storyblok-algolia-indexer@1.0.3
npm WARN   node_modules/storyblok-algolia-indexer
npm WARN     storyblok-algolia-indexer@"^1.0.3" from @nuxtjs/algolia@1.5.0
npm WARN     node_modules/@nuxtjs/algolia
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer axios@"^0.27.2" from storyblok-js-client@4.5.8
npm WARN node_modules/storyblok-algolia-indexer/node_modules/storyblok-js-client
npm WARN   storyblok-js-client@"^4.2.0" from storyblok-algolia-indexer@1.0.3
npm WARN   node_modules/storyblok-algolia-indexer
npm WARN
npm WARN Conflicting peer dependency: axios@0.27.2
npm WARN node_modules/axios
npm WARN   peer axios@"^0.27.2" from storyblok-js-client@4.5.8
npm WARN   node_modules/storyblok-algolia-indexer/node_modules/storyblok-js-client
npm WARN     storyblok-js-client@"^4.2.0" from storyblok-algolia-indexer@1.0.3
npm WARN     node_modules/storyblok-algolia-indexer

  "devDependencies": {
    "@algolia/recommend-js": "^1.3.1",
    "@iconify-json/carbon": "^1.1.11",
    "@iconify-json/mdi": "^1.1.36",
    "@nuxtjs/algolia": "^1.5.0",
    "@pinia/nuxt": "^0.4.6",
    "@unocss/nuxt": "^0.50.6",
    "@unocss/preset-icons": "^0.49.7",
    "@unocss/preset-uno": "^0.49.7",
    "@unocss/preset-web-fonts": "^0.49.7",
    "@vite-pwa/nuxt": "^0.0.5",
    "@vueuse/core": "^9.3.1",
    "@vueuse/nuxt": "^9.3.1",
    "algoliasearch": "^4.13.1",
    "axios": "^1.3.3",
    "instantsearch.css": "^8.0.0",
    "nuxt": "^3.3.1",
    "nuxt-icon": "^0.3.2",
    "pinia": "^2.0.28",
    "search-insights": "^2.2.1",
    "shopify-buy": "^2.17.1"
  }

**Comment by Baroshem** [comment]
Hey @digbyk 

Yes, you are right. This is a bug. I will fix it in the upcoming days.

stay tuned!

**Comment by digbyk** [comment]
Thank you Jakub. I'll give it a try.

**Comment by Baroshem** [comment]
Closing the ticket as there was no further info
