### ISSUE TITLE
SSG crawler support for Nuxt 3

### ISSUE THREAD

**Issue by yahyaio** [nuxt-modules/algolia#144]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
Since SSG crawler support is available for Nuxt 2, I think it would be great to also support Nuxt 3. This would be very convenient for static sites like blogs and docs using [Docus](https://docus.dev).  And would further enhance this module capabilities.

I'm not sure if Nuxt 3 actually supports the hooks required to support this feature. I was not able to find hooks that function the same way as the current hooks: `generate:page` and `generate:done`. But I thought someone else might know the right hooks for this feature.

### Describe alternatives you've considered
Uploading data manually.

### Additional context
[Here](https://github.com/nuxt-modules/algolia/blob/main/src/module.ts#L100) is the current hooks available for Nuxt 2.

Thank you.

**Comment by Baroshem** [comment]
Hey,

Thanks for rising this issue!

@yassilah as the original creator of crawler support, maybe you would be interested in developing a nuxt 3 support? :)

**Comment by yassilah** [comment]
Hey! Sure i'll have a look
