### ISSUE TITLE
[nuxt] [runtimeConfig] You are trying to access a public runtime config value (`algolia`) directly from the top level. This currently works (for backward compatibility with Nuxt 2) but this compatibility layer will be removed in v3.5. Instead, you can update `config['algolia']` to `config.public['algolia']`.

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-modules/algolia#146]
### Version

- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.0`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `vite`, `i18n`, `nitro`, `schemaOrg`, `telemetry`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.6.0`, `formidable@2.1.1`, `nuxt-viewport@2.0.4`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.13.0`, `nuxt-schema-org@2.1.2`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.8`, `@nuxtjs/i18n@8.0.0-beta.10`, `@sidebase/nuxt-auth@0.4.4`
- Build Modules:    `-`

### Reproduction Link

https://stackblitz.com/edit/nuxt-starter-rtn6e3

### What is Expected?

When i upgrade to nuxt 3.4.0 the module of algolia throws 
(node:15923) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1573)
warning:60
[nuxt] [runtimeConfig] You are trying to access a public runtime config value (`algolia`) directly from the top level. This currently works (for backward compatibility with Nuxt 2) but this compatibility layer will be removed in v3.5. Instead, you can update `config['algolia']` to `config.public['algolia']`.

**Comment by agracia-foticos** [comment]
Reproduction LINK

https://stackblitz.com/edit/nuxt-starter-rtn6e3

**Comment by agracia-foticos** [comment]
Fail in stackblitz
![image](https://user-images.githubusercontent.com/77386602/231682254-dca59910-ddb2-4186-b93d-642931493239.png)

**Comment by Baroshem** [comment]
Hey @agracia-foticos 

Thanks for reporting this issue! I will take a look at it in the upcoming days :)

**Comment by RomanSkrypnik** [comment]
Facing the same issue

**Comment by agracia-foticos** [comment]
Works! i close the issue
