### ISSUE TITLE
Disjunctive Facets

### ISSUE THREAD

**Issue by Awais-019** [nuxt-modules/algolia#150]
How can we use disjunctive facets in nuxt algolia module? I  found it in algolia helper but not in Sdk or in this module.

**Comment by Awais-019** [comment]
Here is something I wanna add more I think this module is not available inside server routes in Nuxt3.

**Comment by Baroshem** [comment]
Hey,

Regarding the first question. I dont really know what do you mean by disjunctive facets. I tried to search for this term in Aloglia docs but have not found any info about it. If it is not available in the algolia sdk it will mean that it is not available in this module (as it is a wrapper around the official sdk)

Regarding the second question, yes that is correct. This module does not work in the server endpoints. You can use useAsyncAlgoliaSearch composable that will trigger the request on the server and hydrate the client with this data.
