### ISSUE TITLE
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

### ISSUE THREAD

**Issue by Laureatus** [nuxt-modules/algolia#177]
### Version

@nuxtjs/algolia: v1.9.0
nuxt: v3.7.4

### Steps to reproduce
`npm install`

### What is Expected?
No npm deprecation warnings are visible.
The deprecated module [rollup-plugin-inject@3.0.2](https://github.com/rollup/rollup-plugin-inject)  should be replaced with [@rollup/plugin-inject](https://github.com/rollup/plugins) 

### What is actually happening?
Algolia v1.9.0 is currently using the deprecated module [rollup-plugin-inject@3.0.2](https://github.com/rollup/rollup-plugin-inject)

**Comment by Baroshem** [comment]
Hey, thanks for finding this issue. Would you be interested in creating a fix for it? :)

**Comment by Laureatus** [comment]
Related to this Issue is also the following npm deprecation warning: 
`npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead`

Since sourcemap-codec is a dependency of rollup-plugin-inject replacing the module could resolve this issue too.

**Comment by Laureatus** [comment]
Just saw that `rollup-plugin-node-polyfill` which has the dependencies `rollup-plugin-inject` and `sourcemap-codec` was removed in https://github.com/nuxt-modules/algolia/pull/162. After the release of a new Version, the modules causing the deprecation warnings won't be a part of algolia anymore. Because of that, I'm closing this issue.

**Comment by Baroshem** [comment]
I see. Thanks for that!
