### ISSUE TITLE
How to add facet display?

### ISSUE THREAD

**Issue by IskandarAlex2** [nuxt-modules/algolia#184]
I am trying to make a blog instantsearch page where you can use the search bar to search by title or use facet (Filter) by tags. However, I could not find any facet being mentioned on the documentation page and my VSCode is not helpful because IntelliSense kept saying it could not resolve the module while Nuxt runs perfectly fine with no errors.
![image](https://github.com/nuxt-modules/algolia/assets/65650645/9350e88e-946e-4fe0-a343-4fe21b51a7d0)

**Comment by Baroshem** [comment]
Hey Buddy,

I think you have two cases/questions:

1. Using facets -> Have you tried https://algolia.nuxtjs.org/getting-started/usage#usealgoliafacetedsearch?
2. The error is related to the fact that Vue Instantsearch library provides both cjs and es imports and in order to make it work, I had to import it this way. This is strange but I cannot make it work any other way.

Hope that I helped :)

**Comment by IskandarAlex2** [comment]
Oh I guess that slipped from my eyes, I'll try that then I will tell how it goes. And secondly, there's really no way to make vscode recognize the import as valid? It annoys me a bit

**Comment by IskandarAlex2** [comment]
@Baroshem so I decided to use `useAlgoliaSearch` because the `useAlgoliaFacetedSearch` is only for getting the Facets. However, I am having trouble applying the Facet filter as the [Algolia official documentation shows](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/in-depth/filters-and-facetfilters/#:~:text=So%20the%20equivalent%20facet%20filtering%20for%20the%20above%20is%20as%20follows%3A), it still lists other object that does not have specified facet

```ts
const { result, search } = useAlgoliaSearch("PUBLIC_BLOGS_REGISTRY");

let hits: any[];

onBeforeMount(async () => {
    await search({ query: "", facetFilters: [["tags:happy"]] });
    hits = result.value.hits;
    console.table(result.value.hits);
})
```

**Comment by Baroshem** [comment]
Regarding first question. I dont think there is. Unless maybe there is some tsconfig that I am not aware off.

Regarding second. Have you tried using request options of search method as explained here https://algolia.nuxtjs.org/getting-started/usage/#usealgoliasearch

**Comment by IskandarAlex2** [comment]
so after some messing around trying to find a solution, I finally understand how it works so now it works. Just gonna close this with my code so other people won't be as confused as me
```ts
const { result, search } = useAlgoliaSearch("INDEX_NAME");
await search({ query: input_string, requestOptions: {facetFilters: ["tags:happy"]} });
console.table(result.value.hits);
```

**Comment by JMKelley** [comment]
This really needs to be added to the docs somewhere. Took me a while to hunt this down.

**Comment by Baroshem** [comment]
@JMKelley added in 42ba62813d35f2b3583fb77c964e181f05523eb3 :)
