### ISSUE TITLE
Implement Algolia multipleQueries method

### ISSUE THREAD

**Issue by CedsTrash** [nuxt-modules/algolia#200]
### Is your feature request related to a problem? Please describe.
Nope

### Describe the solution you'd like
I would need to use the multipleQueries method in order to query multiple indexes at once.
https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/

### Describe alternatives you've considered
Use the Algolia Javascript library

### Additional context

Thanks a lot for your work!

**Comment by Baroshem** [comment]
Hey there!

Thanks for your feature request. This is indeed a valid idea. 

Maybe you would be interested in contributing to the module by implementing such feature? I could provide all the help needed :)

**Comment by remihuigen** [comment]
You can use multipleQueries, it's just not documented or typed... You can even use it with the lite configuration

```
const algolia = useAlgoliaRef()
// typescript will give you a warning
const results = await algolia.multipleQueries([
//queries
])

```
